# Generated by Django 4.1.3 on 2022-12-30 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
